### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by deputinizer** [FluxState/ptndown-pia#1]
Thanks for pointing me to db1000n.

I see that you have some experience, so which tool is the best so far? :stuck_out_tongue_winking_eye: 

Also, which file is the 'main' file here in `ptndown-pia` ?

**Comment by FluxState** [comment]
hi np

its a dbkn dockerized for [pia vpn](https://privateinternetaccess.com/) 
```
docker compose build --build-arg PIA_PASS=$PIA_PASS --build-arg PIA_USER=$PIA_USER --build-arg DBN_PROMETHEUS='false'
docker compose up -d --remove-orphans
```
will get you going
https://docs.docker.com/engine/reference/builder/
https://docs.docker.com/compose/

for anti-propaganda proxied mhddos on [those lists](https://github.com/FluxState/warlists)
and a [slimmed version of stoppropaganda](https://github.com/FluxState/stoppropaganda/tree/cleaned4pia)
you can saturate 1Gbps conn with 1x mhddos and 1-2x sp on right kernel and tcp tuning

if you want itarmyua's targets only then mhddos_proxy 
`python3 runner.py -t 2000 --debug --itarmy`

dbkn may be the easiest hands off auto-updating tool but with lower throughput
`db1000n --country-check-retries=1 --prometheus_on=false`

1x mhddos (anti-propaganda) [upload] + 1x sp [download] + 1x dbkn is a nice combo

**Comment by deputinizer** [comment]
> 1x mhddos (anti-propaganda) [upload] + 1x sp [download] + 1x dbkn is a nice combo

 Oh, i forgot about upload :laughing: :rofl:
